maven_layout()

jar_library(name='borderpatrol-core',
  dependencies=[ 'borderpatrol/borderpatrol-core/src/main/scala' ]
)

jar_library(name='tests',
  dependencies=[ 'borderpatrol/borderpatrol-core/src/test/scala' ]
)
