maven_layout()

jar_library(name='borderpatrol-core',
  dependencies=[
    pants('borderpatrol/borderpatrol-core/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('borderpatrol/borderpatrol-core/src/test/java'),
    pants('borderpatrol/borderpatrol-core/src/test/scala')
  ]
)
