# test borderpatrol-core

junit_tests(name='scala',
  dependencies=[
    '3rdparty:junit',
    '3rdparty:mockito-all',
    '3rdparty:scalatest',
    'twitter-server'
  ],
  sources=rglobs('*.scala'),
  resources=['borderpatrol-core/src/test/resources']
)